# Generated by Django 5.1.1 on 2024-10-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparksmodel',
            name='content',
            field=models.TextField(max_length=2000),
        ),
    ]
